/**:
  ros__parameters:
    initial_pose_x: 0.5
    initial_pose_y: 0.5
    initial_pose_yaw_deg: 0.0
    frequency: 100.0
    joint_names : ["swerve_wheel_0", "swerve_wheel_1", "swerve_wheel_base_0", "swerve_wheel_base_1"]
    control_modes : ["speed", "speed", "position", "position"]
    initial_positions : [0.0, 0.0, 0.0, 0.0]
    joint_position_tau : [0.1, 0.1, 0.1, 0.1]
    joint_velocity_tau : [0.1, 0.1, 0.1, 0.1]
    joint_velocity_max : [60.0, 60.0, 10.0, 10.0]